In [2]:
import numpy as np
import numpy.linalg as linalg
#this package is necessary to run the matrix and find the solution of the coefficients in the chemical reaction

In [ ]:
#Three equations: 2 Incomplete Combustions and 1 complete combustions

$$ x_1 NH_3 + x_2 O_2 \rightarrow x_3 NO + x_4 H_2O$$

$$ x_1 NH_3 + x_2 O_2 \rightarrow x_3 N_2 + x_4 H_2O$$

$$ x_1 NH_3 + x_2 O_2 \rightarrow x_3 NO_2 + x_4 H_2O$$

In [23]:
#starting with the one below
#this chemical equation is one of the two incomplete combustion reaction which produced nitrigen monoxide

$$ x_1 NH_3 + x_2 O_2 \rightarrow x_3 NO + x_4 H_2O$$

$$ Nitrogen: 1\bullet x_1+0 \bullet x_2 -1 \bullet x_3 -0 \bullet x_4 =0$$

$$Hydrogen: 3\bullet x_1+0 \bullet x_2-0 \bullet x_3-2 \bullet x_4 =0$$

$$ Oxygen: 0\bullet x_1+2 \bullet x_2-1 \bullet x_3-1 \bullet x_4 =0 $$

In [24]:
#all numbers correspond to the number of atoms are in each side of the equation, the last row is the basis
matrix_A = np.array([[1,0,-1,0],
                     [3,0,0,-2],
                     [0,2,-1,-1],
                     [1,0,0,0]])

# i am printing the matrix to make sure that it looks good before proceeding
print(matrix_A)


[[ 1  0 -1  0]
 [ 3  0  0 -2]
 [ 0  2 -1 -1]
 [ 1  0  0  0]]


In [25]:
vector_b= np.array([0,0,0,1])
#the b maxtrix will be very important factor

In [18]:
new_vector_b = vector_b.reshape(-1,1)
#i am reshaping so it will have the same dimesion as matrix a above

In [19]:
print('original vector b:\n')
print(vector_b)

print('\nnew vector b:\n')
print(new_vector_b)

#printing is very important because I want to know what the output looks 

original vector b:

[0 0 0 1]

new vector b:

[[0]
 [0]
 [0]
 [1]]


In [26]:
inverse_A = linalg.inv(matrix_A)
print(inverse_A)
# this will take the inverse of A

[[ 0.    0.    0.    1.  ]
 [-0.5  -0.25  0.5   1.25]
 [-1.   -0.   -0.    1.  ]
 [ 0.   -0.5   0.    1.5 ]]


In [28]:
vector_x = np.matmul(inverse_A, vector_b)

vector_x
#this will multiple both the inverse of a and multiple the b vector

array([1.  , 1.25, 1.  , 1.5 ])

In [29]:
new_vector_x = np.matmul(inverse_A, new_vector_b)

new_vector_x
#this is the smallest coefficients i received for this chemical reaction, remember if you dont want fractional coefficent you can scale up to have whole number the matrix purpose is to find the smallest coefficent factor not the whole number which is scaler (times 4)

array([[1.  ],
       [1.25],
       [1.  ],
       [1.5 ]])

In [38]:
#new chemical reaction below


$$ x_1 NH_3 + x_2 O_2 \rightarrow x_3 N_2 + x_4 H_2O$$


$$ Nitrogen: 1\bullet x_1+0 \bullet x_2 -2 \bullet x_3 -0 \bullet x_4 =0$$

$$Hydrogen: 3\bullet x_1+0 \bullet x_2-0 \bullet x_3-2 \bullet x_4 =0$$

$$ Oxygen: 0\bullet x_1+2 \bullet x_2-0 \bullet x_3-1 \bullet x_4 =0 $$

In [30]:
matrix_A = np.array([[1,0,-2,0],
                     [3,0,0,-2],
                     [0,2,-0,-1],
                     [1,0,0,0]])

print(matrix_A)

[[ 1  0 -2  0]
 [ 3  0  0 -2]
 [ 0  2  0 -1]
 [ 1  0  0  0]]


In [32]:
vector_b= np.array([0,0,0,1])


In [33]:
new_vector_b = vector_b.reshape(-1,1)

In [34]:
print('original vector b:\n')
print(vector_b)

print('\nnew vector b:\n')
print(new_vector_b)

original vector b:

[0 0 0 1]

new vector b:

[[0]
 [0]
 [0]
 [1]]


In [35]:
inverse_A = linalg.inv(matrix_A)
print(inverse_A)

[[ 0.    0.    0.    1.  ]
 [ 0.   -0.25  0.5   0.75]
 [-0.5  -0.   -0.    0.5 ]
 [ 0.   -0.5   0.    1.5 ]]


In [36]:
vector_x = np.matmul(inverse_A, vector_b)

vector_x

array([1.  , 0.75, 0.5 , 1.5 ])

In [37]:
new_vector_x = np.matmul(inverse_A, new_vector_b)

new_vector_x

array([[1.  ],
       [0.75],
       [0.5 ],
       [1.5 ]])

In [ ]:
#new chemical reaction

$$ x_1 NH_3 + x_2 O_2 \rightarrow x_3 NO_2 + x_4 H_2O$$

$$ Nitrogen: 1\bullet x_1+0 \bullet x_2 -1 \bullet x_3 -0 \bullet x_4 =0$$

$$Hydrogen: 3\bullet x_1+0 \bullet x_2-0 \bullet x_3-2 \bullet x_4 =0$$

$$ Oxygen: 0\bullet x_1+2 \bullet x_2-2 \bullet x_3-1 \bullet x_4 =0 $$

In [41]:
matrix_A = np.array([[1,0,-1,0],
                     [3,0,0,-2],
                     [0,2,-2,-1],
                     [1,0,0,0]])

print(matrix_A)


[[ 1  0 -1  0]
 [ 3  0  0 -2]
 [ 0  2 -2 -1]
 [ 1  0  0  0]]


In [42]:
vector_b= np.array([0,0,0,1])

In [43]:
new_vector_b = vector_b.reshape(-1,1)

In [44]:
print('original vector b:\n')
print(vector_b)

print('\nnew vector b:\n')
print(new_vector_b)

original vector b:

[0 0 0 1]

new vector b:

[[0]
 [0]
 [0]
 [1]]


In [45]:
inverse_A = linalg.inv(matrix_A)
print(inverse_A)

[[ 0.    0.    0.    1.  ]
 [-1.   -0.25  0.5   1.75]
 [-1.   -0.   -0.    1.  ]
 [ 0.   -0.5   0.    1.5 ]]


In [46]:
vector_x = np.matmul(inverse_A, vector_b)

vector_x

array([1.  , 1.75, 1.  , 1.5 ])

In [47]:
new_vector_x = np.matmul(inverse_A, new_vector_b)

new_vector_x

array([[1.  ],
       [1.75],
       [1.  ],
       [1.5 ]])

In [ ]:
#all three species combined NO,NO2, and N2

# Obtain the coefficients in the matrix solution
$$ 1NH_3 +  7/4 O_2 \rightarrow 1 NO_2 + 3/2 H_2O$$ 



$$ 1NH_3 + 3/4 O_2 \rightarrow 1/2 N_2 + 3/2 H_2O$$



$$ 1NH_3 +  5/4 O_2 \rightarrow 1 NO + 3/2 H_2O$$



# combine  all   of  the   equations 

$$ 3NH_3 + 15/4 O_2 \rightarrow 1 NO_2 +1/2 N_2 + 1 NO + 9/2 H_2O $$



# divided   by   three 



$$ 1NH_3 + 5/4 O_2 \rightarrow 1/3 NO_2 + 1/6 N_2 + 1/3 NO + 3/2 H_2O $$